spring:
  security:
    user:
      name: zuoyu
      password: 1230
      roles: USER
  datasource:
    type: org.h2.jdbcx.JdbcDataSource
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql


